---

mysql_info:
  user: devops
  privilege: "*.*:ALL,GRANT"
  database: userdb
  password: redhat
  backupfile: userdb.backup

mysql_packages:
  - mariadb
  - mariadb-server
  - MySQL-python

mysql_services: 
  - mariadb

...